[package]
name = "wordle-helper"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
bitflags = "2.9.1"
bytemuck = "1.23.1"
lexopt = "0.3.1"
rayon = "1.10.0"

[dev-dependencies]
rand = "0.9.1"

[profile.dev]
opt-level = 1
incremental = true

[profile.release]
# lto = true
